### ISSUE TITLE
Rails app inside spec

### ISSUE THREAD

**Issue by hugopeixoto** [procore/blueprinter#100]
There's a rails app living inside `spec/dummy`. From what I can understand, this is so that we can use `ActiveRecord` and `FactoryBot` in `spec/integrations/base_spec.rb` / `context 'Inside Rails project'`.

If this is the case, could we replace it with setting up `ActiveRecord` in a test helper?

**Comment by philipqnguyen** [comment]
Your understanding is correct. A PR for that is welcomed! (get that hacktober shirt!)
