### ISSUE TITLE
Converting null fields to ""

### ISSUE THREAD

**Issue by apcano1978** [procore/blueprinter#114]
Hi, I have a problem, I am trying to use your gem in an API which is already serving data to our customers to make it more performant.

I need to convert nil values in fields to empty string "" instead of null in order to make our response the same we have right now, something like the default value for associations, but for fields.

I don't know if there is a way to do so, I couldn't find it yet. Could anyone guide me?

Thanks in advance

**Comment by mcclayton** [comment]
Hi @apcano1978, thank you so much for creating this issue. I think this is certainly makes sense to support since we already have this functionality for associations. I've got a simple PR that aims to address this: https://github.com/procore/blueprinter/pull/115

**Comment by mcclayton** [comment]
You should now be able to accomplish this in the latest release `0.8.0` using the field-level default option added in: https://github.com/procore/blueprinter/pull/115
