### ISSUE TITLE
Serializing Timestamps as UNIX time.

### ISSUE THREAD

**Issue by michaeldever** [procore/blueprinter#120]
Hi,

I'm just wondering if there's a way to set the default formatting for datetime/time/date objects to be a conversion to unix time, e.g. `time_object.to_i`

I've looked through the source, and the documentation but can't see an example of this, but it would be very useful. More than happy to dig in and submit a PR for this, but didn't want to duplicate work without checking first :)

**Comment by michaeldever** [comment]
Hey @mcclayton,

No worries, yeah, I saw that `datetime_format` but all of our clients consume times/dates as UNIX timestamp integers.

It would be great as if as part of blueprinter configuration, we could do something like:

```
config.generic_formatters = {
  date_time: :to_i,
  time: :to_i,
  date: :to_i
}
```

This would allow users to specify a Proc for more complex formatting if they would like. If these aren't present in configuration, then it would fallback to current behaviour.

We could check for generic formatters by doing something like:

```
generic_formatter_name = "#{object.class.underscore}_formatter".to_sym

if config[generic_formatter_name]
  formatter = config[generic_formatter_name]

  if formatter.respond_to?(:call)
    formatter.call(object)
  else
    object.public_send(formatter)
  end
else
  # Current behaviour
end
```

Such an approach would also allow users to specify generic formatters for objects beyond just the time/date time/date example I'm concerned with.

Let me know what you think, and if you're happy with the above, I can implement this over the holiday period :)

**Comment by michaeldever** [comment]
@philipqnguyen Yes that makes sense, so something like the below:

```
if datetime_format
  object.strftime(datetime_format)
else
  generic_formatter_name = "#{object.class.name.underscore}_formatter".to_sym

  if config[generic_formatter_name]
    formatter = config[generic_formatter_name]

    if formatter.respond_to?(:call)
      formatter.call(object)
    else
      object.public_send(formatter)
    end
  else
    # Current behaviour
  end
end
```

**Comment by philipqnguyen** [comment]
👍 @michaeldever

**Comment by michaeldever** [comment]
@philipqnguyen Haven't had time to look at this yet due to other commitments, but will work on this week after next.

**Comment by mcclayton** [comment]
Hi @michaeldever, sorry for such a long delay on this, but this should now be possible now that
https://github.com/procore/blueprinter/pull/143
and
https://github.com/procore/blueprinter/pull/145
are merged.
Just bump to the latest version of Blueprinter and then you can do set a default datetime configuration in the Blueprinter config as either a string or a proc:
```
Blueprinter.configure do |config|
  config.datetime_format = ->(datetime) { datetime.nil? ? datetime : datetime.strftime("%s").to_i }
end
```
