### ISSUE TITLE
Will this have CLI?

### ISSUE THREAD

**Issue by siba2893** [procore/blueprinter#121]
Hey guys I actually love this gem. But I wonder will this be heavily maintained? and will it have a CLI to generate the blueprints?

**Comment by AllPurposeName** [comment]
This repo will definitely be well maintained. Procore (the company who owns this repo) has [a very extensive REST API](https://developers.procore.com/reference/authentication) which has a very wide variety of serialization requirements. As we adopt Blueprinter universally, we will continue to make our own improvements to it.

Additionally, those of us working closely with the gem are very passionate about the project, and that passion extends past our work duties. As a great example of that you can look at @philipqnguyen one of the core maintainers of Blueprinter who now works at [ResortPass](https://www.resortpass.com/) 😄

CLIs are a great idea! Do you have any thoughts on an ideal usage?

**Comment by siba2893** [comment]
Oh thats so nice to hear!

I'm happy you guys love to code and work on this kind of projects I do that with my projects too.

For the CLI I believe first it should have a generator so you can do something like.

rails g blueprint User name age

And that would create the blueprint under blueprints folder inside app with those fields. What do you think?

**Comment by philipqnguyen** [comment]
is this feature something you'd like to work on @siba2893 ?

**Comment by hugopeixoto** [comment]
Since #176 is merged, can this issue be closed?

I think that the only thing that might be missing is a reference to the generator in the readme / docs.

**Comment by mcclayton** [comment]
Going to close this issue as this has been implemented -- will add an item to the maintainers backlog to get this documented 👍
