### ISSUE TITLE
Polymorphic relations?

### ISSUE THREAD

**Issue by deepeeess** [procore/blueprinter#125]
Hi,

Does blueprinter support polymorphic relations?  Is there a publicly available code example demonstrating this functionality?

Thank you,

Dan

**Comment by philipqnguyen** [comment]
@ritikesh is actually working on a feature that would make serializing polymorphic associations easier. See #122

**Comment by deepeeess** [comment]
Duh, sorry for wasting your time @paigegarnick . Thanks for getting back to me.  Closing.
