### ISSUE TITLE
Bug: Serializing boolean `false` value returns `nil`

### ISSUE THREAD

**Issue by samsongz** [procore/blueprinter#130]
hey team! we found a bug in the serialization of boolean `false` values as follows:

To recreate:

```ruby
TestClass = Class.new(Blueprinter::Base) do
  identifier :id
  field :active
end

data = {
  id: 1,
  active: false
}

TestClass.render(data)

```
The output of `.render` is: `"{\"id\":1,\"active\":null}"`

It is coming from the `extract` method of `HashExtractor`
https://github.com/procore/blueprinter/blob/f2415a3fa0ec835ac12cf39d92974eae14ca879b/lib/blueprinter/extractors/hash_extractor.rb#L1-L7

Because the first condition evaluates to `false` (the correct value to be returned) it evaluates the second, which looks for a string key that doesn't exist, returning `nil`.

I have a branch with a spec to recreate and a suggested fix (remove the second OR condition) that I'd be happy to open a PR for to discuss or get feedback ✌️

**Comment by mcclayton** [comment]
Closing this as it has been fixed in https://github.com/procore/blueprinter/pull/132
