### ISSUE TITLE
Set root node for output JSON

### ISSUE THREAD

**Issue by BatedUrGonnaDie** [procore/blueprinter#134]
I was wondering if it was possible to add the ability to specify a top level root node for the JSON it emits.  I read through the readme and didn't see anything specifying how to do this (although I may have missed it).  I know that AMS supports it by specifying the adapter as json in an initializer and overriding it on a per-serialize basis by specifying it in the render call.

**Comment by philipqnguyen** [comment]
@BatedUrGonnaDie at the moment, there is not a way to specify a root key. @ritikesh is working on a PR to implement this, see #135

**Comment by mcclayton** [comment]
Hey @BatedUrGonnaDie,
this should now be possible with the latest Blueprinter release `0.13.0` thanks to @ritikesh:
https://github.com/procore/blueprinter/pull/135

**Comment by BatedUrGonnaDie** [comment]
I appreciate it a lot all.  And special thanks as well @ritikesh for implementing it.
