### ISSUE TITLE
Add test generator for blueprinter

### ISSUE THREAD

**Issue by HParker** [procore/blueprinter#137]
I believe we have a fairly straightforward way of turning our blueprinter definition into calls to the model being serialized. To make it easier to use ruby objects over AR objects, we could create a test helper like `is_printable_with(PostBlueprinter)` that would assure the methods it plans to call on the model exist on the class under test.

My particular usecase is wanting to include an [active resource](https://github.com/rails/activeresource) as a relation to a AR model and I want to make sure that the active resource has the correct methods and can be serialized by Blueprinter.

Thanks let me know what you think!

**Comment by philipqnguyen** [comment]
I believed we talked about this and we decided to now follow through.
