### ISSUE TITLE
Identifier view has duplicate fields and "default" fields.

### ISSUE THREAD

**Issue by AllPurposeName** [procore/blueprinter#148]
The view_collection `fields_for(:identifier)` call duplicates the identifier field as well as including the `:default` view's fields.

Example:
```ruby
class UserBlueprint < Blueprinter::Base
  identifier(:id)
  field(:first_name)

  view :normal do
    field(:last_name)
  end
end
```
`view_collection.fields_for` with each view passed in:
```ruby
{
  :identifier=>
    [
      {:title=>:id},
      {:title=>:first_name},
      {:title=>:id}
    ],
  :default=>
    [
      {:title=>:id},
      {:title=>:first_name}
    ],
  :normal=>
    [
      {:title=>:id},
      {:title=>:first_name},
      {:title=>:last_name}
    ]
}
```

This is because `identifier_fields + sorted_fields` includes the identifier in the sorted fields.

**Comment by mcclayton** [comment]
Closing this as this will be fixed in the next release `0.17.0`: https://github.com/procore/blueprinter/pull/155
