### ISSUE TITLE
JSONB column types?

### ISSUE THREAD

**Issue by cd-rum** [procore/blueprinter#151]
Any word on how to conditionally include `JSONB` column types?

This doesn't work:
```
field :variable_style, unless: ->(var, _options) { var.variable_style == '' }
```

Still results in:
```
"variable_style": {
  "size": "",
  "style": "",
  "colour": "",
  "family": "",
  "line_height": ""
}
```

**Comment by philipqnguyen** [comment]
You're comparing `variable_style` to an empty string, however `variable_style` is an object containing multiple fields with empty strings.

If I understand correctly, what you're trying to do is to conditionally remove the fields inside `variable_style` completely if they are an empty string?

While not elegant, you should be able to achieve what you're trying to do by digging a level deeper inside `variable_style`. 
Something like this (untested):
```
field :variable_style, unless: ->(var, _options) { var.variable_style = var.variable_style.delete_if {|key, val| val == ''} }
```

**Comment by philipqnguyen** [comment]
I'm going to close this for now. Re-open if you wish to continue discussion.
