### ISSUE TITLE
NoMethodError with namespaced polymorphic associations

### ISSUE THREAD

**Issue by TKB21** [procore/blueprinter#157]
I have a polymorphic association setup between my boards, albums, and artists.  It should also be noted that my serializers are namespaced. Following the docs I have my blueprint setup as so:

```
class Api::BoardSerializer < Blueprinter::Base
  identifier :id

  fields :name, :description, :slug

  association :boardable, blueprint: -> (boardable) { boardable.blueprint }, default: {}
end
```

With this setup I get the error:

```NoMethodError (undefined method `blueprint' for #<Album:0x00007fa530117c68>):```

This is what the parent blueprint looks like:

```
class Api::AlbumSerializer < Blueprinter::Base
  association :board
end
```

**Comment by ritikesh** [comment]
Blueprinter doesn't automagically detect serializer class names for you.

Your `Album` class will need to define a instance method called `blueprint` which will need to return the `Api::AlbumSerializer` class.
```ruby
class Album < ActiveRecord::Base
  def blueprint
    Api::AlbumSerializer
  end
end
```

All your other `boardable` types will also need to define similar instance methods. Pls check `Supporting Dynamic Blueprints For Associations` of the documentation for further information.

**Comment by TKB21** [comment]
Ah! So sorry for overlooking this in the documentation. Thanks for the timely response.
