### ISSUE TITLE
Eager loading problem

### ISSUE THREAD

**Issue by denmarkmeralpis** [procore/blueprinter#160]
I dunno if this issue is valid but here's the definitions I have:

```ruby
# order_group.rb
class OrderGroup < ApplicationRecord
  has_many :orders
end

# order.rb
class Order < ApplicationRecord
  belongs_to :order_group
  has_many :order_lines
  has_many :fees
end

# blueprints

# order_group_blueprint.rb
view :extended do
  association :orders, blueprint: OrderBlueprint, view: :extended
end

# order_blueprint.rb
view :extended do
  association :order_lines, blueprint: OrderLineBlueprint
  association :fees, blueprint: FeeBlueprint
end

# some_controller.rb
...
OrderGroupBlueprint.render_as_hash(OrderManifest.all, view: :extended)
...
```

Now, how do I eager load the `fees` & `order_lines` when using the blueprint `OrderGroupBlueprint`? 

Feel free to close the issue if this is invalid :) Thank you very much

**Comment by denmarkmeralpis** [comment]
Sorry, this is a duplicate issue. 

Referencing this to #96 

Closing this now. Cheers!

**Comment by denmarkmeralpis** [comment]
Finally got a solution

```ruby
field :orders do |b|
  b.orders.includes(:fees, :order_lines)
end
```

Closing this issue now. Thanks

**Comment by tcd** [comment]
@denmarkmeralpis Could you elaborate on your solution?

**Comment by tferrerITBA** [comment]
This isn't a great workaround, as you cannot specify which blueprint to use for that specific field. There has to be a better way.

**Comment by philipqnguyen** [comment]
I'm trying to understand the problem. Is there a reason that you cannot eager load the associations before passing the `ActiveRecord::Relation` object to `SomeBlueprint.render(args)`?
