### ISSUE TITLE
View name is not passed along during association serialization

### ISSUE THREAD

**Issue by AndKiel** [procore/blueprinter#161]
I've decided to switch from AMS to Blueprinter but it seems like the view name is not passed along during association serialization.

In AMS I was able to do:
```render json: tournament, include: %w[competitors rounds rounds.players]```
to get nested associations (they were eager-loaded).

In Blueprinter I tried to get the same results by declaring `:extended` view on the Tournament with the Competitors/Rounds associations, then declaring the same view again in Round but with the Players association.

Server response doesn't include players at all. I was able to catch it thanks to `bullet` as it reported unused eager-loading.

PR in my project:
https://github.com/AndKiel/tournaments-api/pull/1

**Comment by philipqnguyen** [comment]
@AndKiel I just commented on your project's PR https://github.com/AndKiel/tournaments-api/pull/1.

Your association will also need to be explicitly passed the view name
```ruby
association :rounds, blueprint: RoundSerializer, view: :extended
```

Closing for now. Re-open if you are still having trouble.
