### ISSUE TITLE
Implement OJ support

### ISSUE THREAD

**Issue by dlcarter** [procore/blueprinter#17]
Since Oj (https://github.com/ohler55/oj) is popular, performant, and above all FAST, we should either default to use it to serialize if detected, or provide a configuration to be able to set it to use Oj by default.

**Comment by philipqnguyen** [comment]
If it's faster than the json gem, why don't we make it a required dependency?

**Comment by philipqnguyen** [comment]
So after some discussion with @AllPurposeName and @dlcarter we have decided to by default use the json in Ruby standard library (not the gem extension) as the default JSON generator. We would build support for detecting (or configuring) JSON gem or OJ gem in the environment and use it if it exists. JSON gem and OJ gem would not be runtime dependencies in the gemspec.

**Comment by philipqnguyen** [comment]
Oj is now supported and can be configured to be used with Blueprinter, see #54
