### ISSUE TITLE
Handling Arbitrary Keys

### ISSUE THREAD

**Issue by philipbjorge** [procore/blueprinter#170]
Hi There,
We have a usecase where we can have completely arbitrary keys in a Hash but would like to apply a common blueprint to all of the values.

We're currently solving this with a transformer, but it doesn't seem unreasonable to me that this might get included in core?

```
fields *, blueprint: FlavorBlueprint
wildcard_fields blueprint: FlavorBlueprint
```

```
# Transformer for handling hashes with arbitrary keys
# and applying a blueprint to the values
class BlueprintableHashTransformer < Blueprinter::Transformer
  # @param [symbol] field the field that your hash will be extracted from
  # @param [Blueprinter::Base] blueprint the blueprint to apply to all of the hash's values
  # @param [symbol] name if set, this will rename the field in the response
  def initialize(field:, blueprint:, name: nil)
    @field = field
    @blueprint = blueprint
    @name = name || field
  end

  def transform(hash, object, options)
    field_object = extract(@field, object)

    sorted_field_object = field_object.keys.sort.each_with_object({}) do |key, memo|
      memo[key] = @blueprint.render_as_hash(field_object[key])
    end

    hash[@name] = sorted_field_object
  end

  private
    def extract(field_name, object)
      extractor = Blueprinter::AutoExtractor.new
      extractor.extract(field_name, object, {})
    end
end
```

**Comment by philipqnguyen** [comment]
Just clarifying what you're asking... You're asking if it's worthwhile to make a PR introducing the `BlueprintableHashTransformer` and a `fields` that accept wildcards?

**Comment by philipbjorge** [comment]
More or less... yes.

If this isn't an uncommon usecase, is there any interest in supporting this in core with a new method like `any_fields` (or something else)? (I don't think full on globbing/wildcards is necessary)

I wouldn't imagine including the transformer in core would make sense? I'm cool with just leaving that sample code here for the next dev that wonders how they might do this with blueprinter.

**Comment by philipqnguyen** [comment]
Thanks for putting up your solution. Though it is not something that we are considering for right now in core.

Closing for now.
