### ISSUE TITLE
View will ignore  sort_fields_by: :definition

### ISSUE THREAD

**Issue by krtschmr** [procore/blueprinter#172]
Blueprinter.configure do |config|
      config.sort_fields_by = :definition
    end

```
class OrderBlueprint < Blueprinter::Base

  identifier :identifier,  name: :id
  fields :state, :order_type, :market, :volume, :limit, :scheduled_start, :scheduled_end, :volume_filled, :fee, :created_at, :closed_at, :updated_at

  view :extended do
    association :trades, blueprint: TradeBlueprint
  end

end

```

if i call the extended view, it has following output

```
{
  "id": "3R53J-RT8PY-377PBL",
  "trades": [
    .....
  ],
  "state": "closed",
  "order_type": "buy",
....
```

if we define the view like this
```

view :extended do
    fields :state, :order_type, :market, :volume, :limit, :scheduled_start, :scheduled_end, :volume_filled, :fee, :created_at, :closed_at, :updated_at
    association :trades, blueprint: TradeBlueprint
  end
```

it will first outputs the fields, then the association

i would expect the default behavior the have the association at the end

**Comment by krtschmr** [comment]
a quickfix would be the following

```
Blueprinter::Base.class_eval do
  def self.view(view_name)
    @current_view = view_collection[:default]
    yield
    @current_view = view_collection[view_name]
  end
end

```


now, i can just call an association in a view, and it will gets called last. we can't find any sideeffects, so i propose to change it

**Comment by philipqnguyen** [comment]
@krtschmr I tried it myself and confirmed this is a bug. Thanks for reporting.

Accepting PRs to fix this.

**Comment by krtschmr** [comment]
@philipqnguyen  well i posted a fix for this particular problem but i had 7 tests then failed. basically it was just changing the order how it was rendered.  we could then fix the other 7 tests but i'm not deep enough into the gem to see if this is the expected behavior

**Comment by philipqnguyen** [comment]
Haven't tried your solution yet,  but I'll give it a closer look @krtschmr . Although wouldn't your solution always force the view to be at the bottom regardless of sort?

**Comment by krtschmr** [comment]
i guess so. the solution i provided broke a few tests so we need to think and maybe redefine which order do we expect by default and which one do we need to prioritize.
