### ISSUE TITLE
BigDecimal Formatting?

### ISSUE THREAD

**Issue by philipbjorge** [procore/blueprinter#177]
Hi,
We render some responses that occasionally have `BigDecimal` in them which our JSON library will serialize as strings (This is somewhat configurable, but tricky with `Oj` in our rails app).

Is there a good place that we can have blueprinter handle this for us?

It seems like it could be enabled around here similarly to the custom datetime formatting -- https://github.com/procore/blueprinter/blob/4df6de78ed6c1f8574d5ec2fad5d1f4935fdb003/lib/blueprinter/extractors/auto_extractor.rb#L12

Is this something that would be considered to take into core?

**Comment by philipqnguyen** [comment]
The current way is to create your own extractor, ie `CustomExtractor`, and pass it to `field`
``` ruby
field :some_big_decimal_attr, extractor: CustomExtractor.new
```

As an aside, we definitely like your proposal in #178

**Comment by philipqnguyen** [comment]
Closing for now, reopen if you think otherwise.
