### ISSUE TITLE
Configurable Default Extractor?

### ISSUE THREAD

**Issue by philipbjorge** [procore/blueprinter#178]
We're interested in potentially extending the `AutoExtractor` for our usecases and rather than monkey patching are wondering if you'd consider taking a change that makes the default extractor configurable?

https://github.com/procore/blueprinter/issues/177

**Comment by philipqnguyen** [comment]
@philipbjorge sorry for the late reply. Yes I definitely like this idea. Specifically setting a default extractor in the `configuration` would be a good way to go. If not set, it would be the `AutoExtractor`. If you have the time to make a PR for this, we would definitely welcome it.

Apologies for the late response.

**Comment by mcclayton** [comment]
Closing since this has been implemented in: https://github.com/procore/blueprinter/pull/198
