### ISSUE TITLE
Update documentation or fix deprecation notice for field-level conditionals?

### ISSUE THREAD

**Issue by mayesgr** [procore/blueprinter#179]
After updating Blueprinter to 0.19.0 in a Rails app, I'm now seeing the following notice:

``
[DEPRECATION] Blueprinter :if conditions now expects 3 arguments instead of 2.
``

Our Rails app only uses field-level conditional fields and the Blueprinter documentation still gives examples for field-level conditions using two arguments instead of three.  Is the documentation wrong or is the deprecation notice incorrectly displayed for field-level conditionals?  Or is it an error or misunderstanding on my part?

Thanks for this wonderfully clean and easy-to-use gem.

**Comment by mcclayton** [comment]
Thanks for creating this issue @mayesgr, this appears to be an issue with the documentation, as the deprecation notice is correct. Thanks for pointing this out!
