### ISSUE TITLE
Renaming field

### ISSUE THREAD

**Issue by kenzo2013** [procore/blueprinter#188]
Hello I'm using blueprinter with grape on my project. I 'm trying to rename a field like this field :score, name:  :compliance_scores, but the field not apppears on hash. 

Please any help?

**Comment by philipqnguyen** [comment]
Hi @kenzo2013 

What do you mean when you say the "the field not apppears on hash"? 
Did you use `render` or `render_as_hash`? Could you if possible, paste your Blueprint file?

**Comment by dlcarter** [comment]
We're going to close out this issue due to inactivity. If you feel like this is still a valid issue, feel free to comment!
