### ISSUE TITLE
Issue with include_view order and field/association redefinition

### ISSUE THREAD

**Issue by Berardpi** [procore/blueprinter#200]
Hello!

We have a case where we use the same association several times in a Serializer, with different views. Because of order in which `include_view` works, the specified view is sometimes not respected:

```ruby
class Serializer
  association :children

  view :extended do
    association :children, view: :extended # This works
  end

  view :community do
    include_view :extended
    association :children, view: :community # This will render children with the extended view and not the community
  end
end
```

I'm open to make a PR to change the inclusion order. I wanted to check with you beforehand, because this may be a breaking change since it will change the redefinition order.

What do you think?

**Comment by anlek** [comment]
I'd love to see this even for things like `field`.
Let me know if there is anything I can do to help.

**Comment by kbonnin** [comment]
It's been over a year and the PR seems to have been approved. What is blocking it from being merged ?

I would love for this issue to be fixed as well, being able to redefine fields or associations in views seems like an important feature.
