### ISSUE TITLE
[Question] Associations specifying blueprint view

### ISSUE THREAD

**Issue by rwehresmann** [procore/blueprinter#209]
Let's suppose that I have a `CurrencyBlueprint` with a view named `simulator`. My `DocumentBlueprint` has an association with `Currency`, so I specify

```ruby
association :currency, blueprint: CurrencyBluePrint
```

Is it possible somehow specify in this association that I wanna use the view `simulator` from my `CurrencyBluePrint`? E.g.:

```ruby
association :currency, blueprint: CurrencyBluePrint, view: :simulator
```

**Comment by leonhess** [comment]
According to #190 and the [documentation ](https://www.rubydoc.info/gems/blueprinter/Blueprinter/Base#association-class_method) you can do that like you have shown.
