### ISSUE TITLE
Possibility to request multiple views

### ISSUE THREAD

**Issue by tomasdundacek** [procore/blueprinter#212]
Hi folks,

Firstly, thanks for this great gem, it is a pleasure to work with it!

However, I was wondering, whether you have considered allowing the `view` option to take in an array instance. Do you have any position on this? 🙂

**Example usage**
`EventSerializer.render(event, views: [:with_invitations, :with_reactions])`

**Current workaround**
Currently, I am able to work around this problem like this:

```ruby
class EventSerializer < Blueprinter::Base
  ...

  view :with_invitations do
    ...
  end

  view :with_reactions do
    ...
  end

  view :with_invitations_and_reactions do
    include_view :with_invitations
    include_view :with_reactions
  end
end
```

Thanks
Tomas

**Comment by mcclayton** [comment]
Hey @tomasdundacek, thank you for reaching out 👋
The Blueprinter maintainer team discussed this, and our position is that the workaround you listed is actually our encouraged approach. I'm going to close this issue as this isn't something we plan to implement, but please feel free to re-open if you have any further questions!

**Comment by anlek** [comment]
Hello @mcclayton, I'm trying to understand better this choice, can you give a bit more details on why it's the encouraged approach?

It seems to me if you have 4 views and you want to support a blend of those views, you'd need to create 15 view combinations to make it work. if you have 5 views, you're looking at 31 combinations...  Where if I could say `view: [:view_1, :view_2]` or `view: [:view_2, :view_5]` gives the developer power without having to hard code all the possible combinations.

Just trying to understand,
Andrew

**Comment by dlcarter** [comment]
Hi @anlek, I agree with you that it would give the developer much more flexibility to be able to dynamically pass in views to be determined at render time. However, one of the design goals we've had for Blueprinter is to be simple and clear as to what's happening. Adding a dynamic combination of views for a single render can quickly get very messy and unclear. However, I am open to compelling use cases for the dynamic approach that could help us see other aspects to this concept.
