### ISSUE TITLE
How to group multiple fields?

### ISSUE THREAD

**Issue by taschetto** [procore/blueprinter#215]
Hi. Is is possible to create a field to group other fields?

Example: model `User` with fields `first_name`, `last_name`, `created_at`, `updated_at`.

Desired output:

```
{
  :id => "d89dcd53-96f6-4795-8e63-a03a50596b16",
  :attributes => {
    :email => "arlinda@example.org",
    :first_name => "Leonardo",
    :last_name => "Quaresma"
  },
  :meta => {
    :created_at => Mon, 04 May 2020 17:59:27 -03 -03:00,
    :updated_at => Mon, 04 May 2020 17:59:27 -03 -03:00
  }
}
```

I've achived this using the following code. But I wanted to know if there's a native API to this library to do that.

```ruby
class UserSerializer < Blueprinter::Base
  identifier :id

  field :attributes do |object|
    {
      email: object.email,
      first_name: object.first_name,
      last_name: object.last_name,
    }
  end

  field :meta do |object|
    {
      created_at: object.created_at,
      updated_at: object.updated_at,
    }
  end
end
```

**Comment by mcclayton** [comment]
For your specific use case, I believe what you've done is what I'd recommend. 
We don't provide a native field grouping api quite like what you're describing.
We do have the `root` key for wrapping all of the fields in a key -- but that's not exactly what you're looking for.

**Comment by taschetto** [comment]
Thank you, Michael. Best regards.
