### ISSUE TITLE
Pass options to nested association

### ISSUE THREAD

**Issue by Tao-Galasse** [procore/blueprinter#216]
Hi!

I would like to pass options from a blueprint to another one, via an association.

For example:

```ruby
class UserBlueprint
  association :articles, blueprint: ArticleBlueprint, options: {dummy_option: 'foobar'}
end

class ArticleBlueprint
  field :something do |article, options|
    # use data in options here
  end
end
```

I know I can't use the `options` param in the UserBlueprint, but I don't know how to do it. Can someone help me? :)

**Comment by selivandex** [comment]
Did you found solution?

**Comment by Tao-Galasse** [comment]
No, I didn't 😕

**Comment by schodevio** [comment]
It would be nice to have, any solutions or workarounds?

**Comment by schodevio** [comment]
This is my temporary solution, any better ideas?

```ruby
class UserBlueprint
  # collection
  field :articles do |user, options|
    ArticleBlueprint.render_as_hash(user.articles, **options)
  end

  # single model ex. user belongs to a team
  field :team, default: {} do |user, options|
    next if user&.team.blank? 

    TeamBlueprint.render_as_hash(user.team, **options)
  end
end

class ArticleBlueprint
  field :something do |article, options|
    # use data in options here
  end
end

class TeamBlueprint
  field :something do |team, options|
    # use data in options here
  end
end
```

**Comment by philipqnguyen** [comment]
Currently blueprinter does not support what you're asking. I can try and work on this when I have time or if someone wants to contribute and make a PR for this, that would be helpful!

The area of code that handles this is here. It's a bit confusing, but `local_option` are the options given to `render`, while the `option` are the options given to `field` or `association`.
https://github.com/procore/blueprinter/blob/32fd661905b05a8428a70be3c4025657fedb2fbf/lib/blueprinter/extractors/block_extractor.rb#L4-L6

**Comment by philipqnguyen** [comment]
Actually to achieve exactly what you're looking to do, you can override the current `BlockExtracctor` by adding this to an initializers file:
``` ruby
module Blueprinter
  class BlockExtractor < Extractor
    def extract(field_name, object, local_options, options = {})
      options[:block].call(object, local_options.merge(options))
    end
  end
end
```

----

As for introducing this into blueprinter itself, as I'm thinking about it more, it could cause a breaking change. Maybe it's worth the breaking change. Unless if there's another solution that won't break.

**Comment by mcclayton** [comment]
Another potential solution (_hack_) would be to define an association field and mutate the association options directly, as these will end up getting passed to the associated blueprint. 
i.e.
```
class UserBlueprint
  association :articles, blueprint: ArticleBlueprint do |user, options|
    options.merge!({ dummy_option: 'foobar' })
    user.articles
  end
end

class ArticleBlueprint
  field :something do |article, options|
    # use data in options here
  end
end
```

**Comment by mcclayton** [comment]
I also opened up a PR with one way to implement this. Please let me know if something like the following:
https://github.com/procore/blueprinter/pull/220

does what you would need it to.

**Comment by mcclayton** [comment]
Hi @Tao-Galasse, 
This is now possible as of version `0.24.0` now that https://github.com/procore/blueprinter/pull/220 has been merged. Thanks for reaching out and creating the issue! Going to go ahead and close this now 🙂
