### ISSUE TITLE
Allow defining a transformer used by all views in a blueprint

### ISSUE THREAD

**Issue by supremebeing7** [procore/blueprinter#221]
I generally want all of my snake_cased ruby to be transformed to lowerCamelized JSON. I [commented on another issue](https://github.com/procore/blueprinter/issues/158#issuecomment-580399796) about how I've created a BaseBlueprint from which all other blueprints inherit, and that BaseBlueprint has a lower camel transformer, thereby making it so any new blueprint will automatically transform fields. However, when defining `views` inside the blueprint, it doesn't respect this outer transformer, so I have to add `transform LowerCamelTransformer` inside every single view. 

Is there some configuration either app-wide or even just something I could put in my BaseBlueprint to ensure that all views use the transform added outside of the view unless otherwise specified?

**Comment by supremebeing7** [comment]
Actually, I think I have a simple solution: allow for defining a default transformer in the config. Testing it locally and it seems to work, while still allowing to override with a different transformer as needed. I'll clean it up and post a PR.

**Comment by mcclayton** [comment]
Hi @supremebeing7, thanks for bringing this up 🙂  As you've found, this is not currently supported but as you've also found, can easily be added to the config. I'll be happy to take a look at the PR once you've got it up! Thanks for your willingness to contribute!

**Comment by supremebeing7** [comment]
Thanks @mcclayton. PR is up - #222
