### ISSUE TITLE
Association blueprint 

### ISSUE THREAD

**Issue by CarlosUvaSilva** [procore/blueprinter#223]
First let me say: Really good gem :+1: 

small question though

The documentation for *Rename* states
`association :user_projects, name: :projects`

But after for *Association* it says
`association :projects, blueprint: ProjectBlueprint`

I'm trying to implement an association and just do `association :projects` but it doesn't seem to work wihout specifying the blueprint needed. Is this really necessary? is there a "typo" on the rename documentation or is it something on my code?

Thank you

**Comment by philipqnguyen** [comment]
you do need the `blueprint` argument. Currently the gem does not infer which blueprint to use, so you must specify. 

Will accept changes to documentation to make this clearer.

Closing for now, re-open if you wish to discuss further.
