### ISSUE TITLE
Typecast/coerce value to type other than string or custom formatter

### ISSUE THREAD

**Issue by ychaker** [procore/blueprinter#226]
First of all, thank you for your hard work and making this gem available.

I noticed that all values get returned as a `String`, is there a way to make sure that fields have a different type, mainly numbers (`int`/`float`/`decimal`) and potentially boolean value?

if it's not possible to do, would I be able to use a custom formatter (the way the custom date formatter works) to achieve this?
if yes, would you be able to give me example of what I need to do to introduce a new custom formatter?

Thanks!

**Comment by ychaker** [comment]
so, it turns out the issue is that all of the numbers that I get back are `BigDecimal` numbers and the default serialization of `BigDecimal` in rails is to string.

however, according to the `oj` docs I'm supposed to be able to set something like 

```rb
Oj.default_options = {
  bigdecimal_as_decimal: true
}
```

and it should return a number and not a string, but that's not working.

so I looked at the code further at what the examples from the `oj` issues/docs had different and noticed that they were using the `dump` method instead of the `generate` method, and they were calling `Oj.optimize_rails` before calling `dump`.

so I monkey patched blueprinter like this:

```rb
# frozen_string_literal: true

require 'oj'

Oj.default_options = {
  mode: rails,
  bigdecimal_as_decimal: true
}

Blueprinter.configure do |config|
  config.generator = Oj # default is JSON
  config.method    = :dump
end

module OjOptimizer
  def jsonify(blob)
    Oj.optimize_rails
    super
  end
end

module Blueprinter
  class Configuration
    prepend OjOptimizer
  end
end
```

and that gave me the result I was expecting. But that didn't sit well with me, I didn't want to have to do this, so I looked further and realized that I could use the `:custom` mode instead of the `:rails` mode and supposedly achieve the same thing. so I updated the initializer to this:

```rb
Oj.default_options = {
  mode: :custom,
  bigdecimal_as_decimal: true,
  time_format: :ruby
}

Blueprinter.configure do |config|
  config.generator = Oj # default is JSON
  config.method    = :dump
end
```

and that gave the same result (except that timestamps lose the millisecond precision, which I think I can live with).

I hope that helps the next person that has to deal with this.

**Comment by philipqnguyen** [comment]
Thanks for the solution!
