### ISSUE TITLE
Blueprinter not returning methods/fields

### ISSUE THREAD

**Issue by mikeyduece** [procore/blueprinter#229]
Fields/associations defined in the blueprint are not being returned in the JSON, as well as any method defined in the class. 

For ex.
```ruby
class UserBlueprint < BlueprinterBase
  identifier :slug, name: :id

  fields :first_name, :last_name, :full_name, :formatted_dob

  association :locations, name: :location, blueprint: LocationBlueprint do |user, _options|
    user.locations.first
  end
end
```

The fields that are defined in the schema are `:slug, :first_name, :last_name` and those get returned fine. But the `:formatted_dob` and `:full_name` are defined as instance methods on the model. These are not getting returned. Also, the association defined in the blueprint is not being returned either. 

I am calling the blueprint through a helper method, but I don't think that should be an issue. I have never had this problem until today and can't seem to find out why.

```ruby
# helper method definition
def serialized_resource(resource, blueprint, options = {})
  JSON.parse(blueprint.render(resource, options))
end

# called in the controller with...
render json: { users: serialized_resource(User.all, UserBlueprint) }
```

And the return is:
```json
"users": [
  {
    "id": "45hsadfknadsf98hasn",
    "first_name": "FirstName",
    "last_name": "LastName"
  },
  ...
]
```

**Comment by adamwells** [comment]
It's hard to say what's going wrong for you, but I don't believe it's a blueprinter bug.  I'm able to do what you're describing with the following:

```rb
require 'blueprinter'
require 'json'

class User
  attr_accessor :slug, :first_name, :last_name

  def self.all
    [User.new('my slug', 'my first', 'my last')]
  end

  def initialize(slug, first_name, last_name)
    @slug = slug
    @first_name = first_name
    @last_name = last_name
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def locations
    [{ id: 1 }, { id: 2 }]
  end
end

class LocationBlueprint < Blueprinter::Base
  identifier :id
end

class UserBlueprint < Blueprinter::Base
  identifier :slug, name: :id

  fields :first_name, :last_name, :full_name
  association :locations, blueprint: LocationBlueprint
end

def serialized_resource(resource, blueprint, options = {})
  JSON.parse(blueprint.render(resource, options))
end

p serialized_resource(User.all, UserBlueprint)
```

And it yields exactly what you'd expect
```rb
[{"id"=>"my slug", "first_name"=>"my first", "full_name"=>"my first my last", "last_name"=>"my last", "locations"=>[{"id"=>1}, {"id"=>2}]}]
```

For the computed fields it's hard to say what's wrong, as you can see the example above works.  For the association I can say it does look a bit odd to me in that you're giving an association for a collection with a blueprint, but including a block that yields a single record from it.

**Comment by philipqnguyen** [comment]
@mikeyduece what version of blueprinter are you using?

**Comment by mikeyduece** [comment]
@philipqnguyen , I just updated to 0.25.0 and still getting the same issue. @adamwells , Ya it's a bit wonky. But I'm trying to serialize the return to match whats working in the client already. I will keep digging around, this is pretty weird. Checked in another project and it's working as intended there. So there must be something different, I'm just having a super hard time finding the disconnect :(

**Comment by mikeyduece** [comment]
think I narrowed it down. I had ` config.unless = ->(field_name, obj, _options) { obj[field_name].nil? }` because I keep getting undefined method for nil class without it. Tried setting `config.field_default` and `config.association_default` but still getting the no method error

**Comment by adamwells** [comment]
@mikeyduece There couldn't be something overwriting `public_send` for that model or something, could there? Trying to think of any way that those methods could work but not get serialized

**Comment by mikeyduece** [comment]
@adamwells as far as overwriting `public_send`, I'm not sure. To my knowledge no one has done that for any models

**Comment by adamwells** [comment]
@mikeyduece mind pasting your full config here?

**Comment by mikeyduece** [comment]
@adamwells 
```ruby
Blueprinter.configure do |config|
  config.unless = ->(field_name, obj, _options) { obj[field_name].nil? }
end

```

**Comment by philipqnguyen** [comment]
@mikeyduece if it's a method, the `obj[field_name].nil?` would not work.

Try
```
config.unless = ->(field_name, obj, _options) { obj.public_send(field_name).nil? }
```

**Comment by mikeyduece** [comment]
@adamwells That did it! Can you elaborate why `obj.public_send(field_name).nil?` and `obj[field_name].nil?` doesn't? Will that also work for columns that are nil?

**Comment by adamwells** [comment]
I think the problem was just that the method names aren't accessible via `[]` in ruby, so `[]`ing them always returns nil.  `public_send` actually invokes them if they exist and returns the result, which in this case is actually present

**Comment by mikeyduece** [comment]
Ahh gotcha! That makes total sense. Thanks so much for the help and **super** fast responses. You've saved my day!

**Comment by mikeyduece** [comment]
@adamwells , sorry to bother again. But with this fix, I'm having issue defining fields or associations in the view. It keeps coming back as undefined method. I will continue to work through it but was hoping you or someone might have some thoughts
