### ISSUE TITLE
How can I pass in a parent object into its association blueprint?

### ISSUE THREAD

**Issue by supremebeing7** [procore/blueprinter#237]
I have a has_many/belongs_to association like this:
```ruby
class Foo
  has_many :bars
end

class Bar
  belongs_to :foo
end
```
and I have a Bar blueprint
```ruby
class BarBlueprint < Blueprinter::Base
  identifier :id
  association :foos, blueprint: FooBlueprint
end
```
In my FooBlueprint, I want to get the specific Bar instance that called the association, e.g.
```ruby
class FooBlueprint < Blueprinter::Base
  identifier :id
  field :bar_name do |foo|
    foo.bar.name
  end
end
```
but obviously that won't work because `foo` has many `bars`. I see something in the docs about passing in an option to an association, and that seems like the place to do this, but I'm not sure how to get the instance of `bar` in there. I'm envisioning something like:
```ruby
class BarBlueprint < Blueprinter::Base
  identifier :id
  association :foos, blueprint: FooBlueprint, options: { bar: #what goes here?# }
end
```

I suppose I could flatten my JSON instead of sideloading serialized associations, but it seems like there must be a way to do this. Any ideas here?

**Comment by adamwells** [comment]
Is this something you could solve by using a custom field with options instead of an association?

For example, something like
```rb
class BarBlueprint < Blueprinter::Base
  identifier :id

  field :foos do |bar|
    FooBlueprint.render(bar.foos, view: :normal, bar: bar)
  end
end

class FooBlueprint < Blueprinter::Base
  identifier :id

  view :normal do
    field :bar_name do |_foo, options|
      options[:bar].name
    end
  end
end
```

**Comment by supremebeing7** [comment]
@adamwells Yeah, that would work. I hadn't thought of that. Thanks!
