### ISSUE TITLE
Unnested associations

### ISSUE THREAD

**Issue by thec0keman** [procore/blueprinter#238]
Is it possible with blueprinter to serialize associations in the root?

For example:
```
{
  user: {
    id: 1,
    name: 'Foo',
    commentIds: [1,2,3]
  },
  comments: [
    { id: 1, text: 'Hello },
    { id: 2, text: 'Hello },
    { id: 3, text: 'Hello }
  ]
}
```

If your serializers do not render with a root, this is possible manually with:
```
{
  user: UserSerializer.render_as_hash(user),
  comments: CommentSerializer.render_as_hash(user.comments)
}
```

(This obviously gets a little more complicated with a collection.)

Does Blueprinter support this kind of payload?  Thanks!

**Comment by dlcarter** [comment]
Hey @thec0keman, if I'm understanding your ask correctly, one way to accomplish what you're looking for is by creating a _third_ blueprint, i.e. UserCommentsBlueprint, which includes associations/fields for both of these records.

**Comment by swiknaba** [comment]
```ruby
class UserSerializer
  view :with_comments do
    association :comments, blueprint: CommentSerializer
  end
end
```

```ruby
render json: UserSerializer.render(user, view: :with_comments, root: :user)
```


without testing, this should work.

**Comment by mcclayton** [comment]
I believe this can be closed as @dlcarter's suggestion makes sense. Please comment here if you still have issues with this. Thanks!
