### ISSUE TITLE
Nested Fields

### ISSUE THREAD

**Issue by tenpaiyomi** [procore/blueprinter#239]
Is it possible to have nested fields within a given view?  Specifically, I am trying to use blueprinter to handle displaying the data of a model in addition to a field, `status`, that internally has `complete` and `percentage` fields, like so `status: { complete: false, percentage: 50 } `

When doing a test to see if I can place a field within a field, the value of the parent field is just a blueprinter field object.

**Comment by dlcarter** [comment]
Hey @tenpaiyomi, you should be able to accomplish this like so:
```rb
class UserBlueprint < Blueprinter::Base
  identifier :uuid
  field :status do |user, options|
    {
      complete: user.complete, 
      percentage: user.percentage
    }
  end
end
```

You could also accomplish with a nested blueprint or association.

**Comment by tenpaiyomi** [comment]
Hey @dlcarter, thanks for the response!  I've done it via the `field` with a hash which works.  This is a smaller example of some similar situations, so not _super_ ideal, but can be done as a last resort.

Do you possibly have an example for utilizing a nested blueprint?  I know that there is the association that can be utilized with specifying a blueprint for said association (though not sure about utilizing it or an association in a nested manner).

To give an idea of the logic behind this, we have some models that need to be serialized in certain ways depending on how they are used, including adding some extraneous fields for specific utilizations.  I'm separating these different scenarios out, currently, as just different views, though I may break them out into different blueprints that inherit from a shared parent blueprint.  The problem, however, is that a lot of these extraneous fields are setup in ways that contain a lot of nested information.  So, using the `status` example above for a hypothetical scenario, there might be a third field, `history`, that would contain a hash of objects themselves. 

Instead of having to write everything under `status` as a raw hash, it would be nice to be able to say "ok, the field `status` has a field `complete` and `complete` that have their respective values, and then another field, `history`, that itself has the fields ...."

Hopefully that makes sense!

**Comment by adamwells** [comment]
For a nested blueprint on the example above, it would look something like:
```rb
class UserBlueprint < Blueprinter::Base
  identifier :uuid
  field :status do |user, options|
    StatusBlueprint.render(user.status)
  end
end
```
or if. you were to use an association
```rb
class UserBlueprint < Blueprinter::Base
  identifier :uuid
  association :status, blueprint: StatusBlueprint
end
```
And within e.g. the status blueprint, you can create conditional fields if there are some that you only sometimes want
```rb
class StatusBlueprint < Blueprinter::Base
  field :complete
  field :percentage
  field :history, if: ->(_field_name, status, _options) { status.history.present? }
end
```

Between those, are you able to achieve what you're trying?

**Comment by tenpaiyomi** [comment]
@adamwells that might be perfect!  It's been a bit since I touched the code in question, so I'll have to dig it up and check again.  Thank you for the response!

**Comment by adamwells** [comment]
Cool, if that sounds like it may solve it I'm going to go ahead and close this issue for now, but feel free to reopen or open a new one if something similar comes up again. Thanks!
