### ISSUE TITLE
Global Transforms causing a Rails deprecation warning

### ISSUE THREAD

**Issue by aarona** [procore/blueprinter#240]
I'm getting a deprecation error (see below) when I use Blueprinter in my specs for creating json request hashes. The work-a-around obviously is to use `transform LowerCamelTransformer` in each of my serializer classes. Just wanted you to be aware of this error.

**/app/serializers/lower_camel_transformer.rb:**

```ruby
class LowerCamelTransformer < Blueprinter::Transformer
  def transform(hash, _object, _options)
    hash.transform_keys! { |key| key.to_s.camelize(:lower).to_sym }
  end
end
```

**/config/initializers/blueprinter.rb:**

```ruby
Blueprinter.configure do |config|
  config.default_transformers = [LowerCamelTransformer]
end
```

**Warning I receive when running rspec:**
```
DEPRECATION WARNING: Initialization autoloaded the constant LowerCamelTransformer.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload LowerCamelTransformer, for example,
the expected changes won't be reflected in that stale Class object.

This autoloaded constant has been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <top (required)> at /home/aaron/projects/clients/appt/config/environment.rb:7)
```

**Comment by dlcarter** [comment]
Thanks for bringing this to our attention, we'll work on updating this!

**Comment by aarona** [comment]
Thanks! This is a great gem btw. I'm using it in combination with FactoryBot to create GraphQL request specs.

**Comment by anlek** [comment]
@aarona I believe this is because you're referring to a model that hasn't been loaded via autoloader (which I believe loads after initializers). To fix this, just require it at the top of your file. `require 'lib/lower_camel_transformer'` (or wherever it's located in your source code)

**Comment by mcclayton** [comment]
Hi @aarona, this appears to be outside the responsibility of Blueprinter, and you ought to be able to address this with the solution @anlek mentioned above. I'm going to go ahead and close this issue, but please re-comment if you still have issues with this!

**Comment by FlandersBurger** [comment]
This worked for me:

`
Rails.application.reloader.to_prepare do
  Blueprinter.configure do |config|
    config.default_transformers = [LowerCamelTransformer]
  end
end
`
