### ISSUE TITLE
Is it possible to provide a Proc along with a if? 

### ISSUE THREAD

**Issue by Bennet-Sunder** [procore/blueprinter#244]
Is it possible to do something like this?

`field(:user_name) { |user| user.name } , if: ->(_field_name, _user, _options) { user.active? }`

From the docs, I can see that we can pass a Proc but not sure if we can pass it along with an `if`

**Comment by VvanGemert** [comment]
Hi Bennet-Sunder,

Yes you can. You will need to add the if construct inside the field method and then create a block afterward. 
The syntax will be something like this:

```
field(:user_name, if: ->(_field_name, user, _opts) { user.active? }) do |user, _options|
  user.name
end
```
