### ISSUE TITLE
Sort collection by field when defining association

### ISSUE THREAD

**Issue by leonhess** [procore/blueprinter#262]
Hey,

I have the following problem:

Let's say I have 2 models: questions and slides. In the respective controller I pass the collection of questions to the `QuestionBlueprint` in a sorted fashion:

````
render json: QuestionBlueprint.render(questions.order(position: :asc), view: :normal, root: :questions)
````

This ensures that the questions in the resulting json are sorted by the `position` field.

Now let's say I also have a `SlideBlueprint` that has associated questions:

````
class SlideBlueprint < Blueprinter::Base
  identifier :id

  association :questions, blueprint: QuestionBlueprint, view: :normal
end
````

Here I don't have any control over how the collection of questions is sorted. This results in potentially unsorted questions when using the `SlideBlueprint`. My current idea is using a custom transformer to sort the questions hash before passing it to serialization. Is there a better way to tell blueprinter to sort a associated collection by a certain field?

**Comment by mcclayton** [comment]
Hey @leonhess, could you try doing something like the following?

```rb
class SlideBlueprint < Blueprinter::Base
  identifier :id

  association :questions, blueprint: QuestionBlueprint, view: :normal do |slide, options|
    slide.questions.order(position: :asc)
  end
end
```

**Comment by leonhess** [comment]
Thanks for the quick reply. Your suggested solution worked like a charm. Thanks, closing this issue.
