### ISSUE TITLE
What does the identifier do?

### ISSUE THREAD

**Issue by Frexuz** [procore/blueprinter#271]
```
class Api::V1::UserSerializer < Blueprinter::Base
  identifier :id
end
```

vs

```
class Api::V1::UserSerializer < Blueprinter::Base
  fields :id
end
```

**Comment by mcclayton** [comment]
Hi @Frexuz,  

`identifier` is a purely a developer convenience for being able to create a Blueprinter field that:

1. Get's added to the `default` view, and therefore will be included in all renders by default
2. By default Blueprinter sorts rendered keys by name, however, the `identifier` field is always sorted as first in the list.

If you do not want either of the above developer conveniences, you do not *need* to specify an identifier field.

**Comment by kg-currenxie** [comment]
@mcclayton cool, thanks for the explanation :) Would be nice in the readme 👌 Can close this one :)

**Comment by mcclayton** [comment]
Closing and documenting identifiers in the README [here](https://github.com/procore/blueprinter/pull/274) 🎉
