### ISSUE TITLE
Just a thank you! 🎉

### ISSUE THREAD

**Issue by elvinaspredkelis** [procore/blueprinter#280]
I just wanted to say **thank you**! 🎉 ❤️ 

It took me 15-20 minutes to build what it took me 2 days to build with the rails' native JBuilder. It's faster, the code is much cleaner, easier to maintain and there's much less of it. Amazing!

P.s. you guys don't seem to have a discussion forum here on github, so I resorted to opening an issue.

**Comment by philipqnguyen** [comment]
@elvinaspredkelis This is very heartwarming and I'm glad you found this gem useful. I'll go ahead and close this now :)
