### ISSUE TITLE
is there a way to delegate the options for nested associations?

### ISSUE THREAD

**Issue by amrelhewy09** [procore/blueprinter#298]
I couldn't find this anywhere, any way to delegate the options so I can pass it down multiple associations?

**Comment by jandresrodriguez** [comment]
@amrelhewy09 how did you solve this ?

**Comment by wujibear** [comment]
@amrelhewy09 how???

**Comment by CaptainJNS** [comment]
@jandresrodriguez, @wujibear
Maybe [this](https://github.com/procore-oss/blueprinter/issues/265) will help you
