### ISSUE TITLE
Is `Base.include_associations` working as intended?

### ISSUE THREAD

**Issue by philipqnguyen** [procore/blueprinter#42]
Several questions were raised after reviewing `Base.include_assocations` with @AllPurposeName. Here they are:
- [ ] Is it working as intended?
- [ ] Does it belong in `Base` or does it belong in another class? Perhaps in `Optimizer` class? If it belongs somewhere else, let's move it.

**Comment by mcclayton** [comment]
This can be closed as this functionality was removed in: https://github.com/procore/blueprinter/pull/139
