### ISSUE TITLE
`Base.object_to_hash` should be moved

### ISSUE THREAD

**Issue by philipqnguyen** [procore/blueprinter#47]
We should experiment with moving `jsonify`/`object_to_hash` to a another class. Whether it should be in an existing class like `ViewCollection`  or whether it should be in a new class specific to transforming the object to a hash and json.

**Comment by mcclayton** [comment]
@philipqnguyen 
Do you think this can be closed now that this has been moved to `base_helpers`?
https://github.com/procore/blueprinter/blob/master/lib/blueprinter/helpers/base_helpers.rb#L46-L51

**Comment by philipqnguyen** [comment]
Yes.
