### ISSUE TITLE
ActiveRecord Optimization

### ISSUE THREAD

**Issue by philipqnguyen** [procore/blueprinter#69]
When it comes to ActiveRecord objects, Blueprinter should not need to load all columns to extract values, it should only need to select the columns it needs as specified in the Blueprint. This would reduce the time spent querying the database as well as reducing memory footprint.

**Comment by philipqnguyen** [comment]
You're right, this would be quite tricky. Totally open to ideas on this one. It would be a bad experience if the optimization works for some cases and not for others...

Just an idea, what if we explicitly specify which fields to load in the Blueprint? If no specification is made, we simply load all fields. For example:

```ruby
class UserBlueprint < Blueprinter::Base
  select_fields :uuid, :first_name, :last_name # something like this?

  identifier :uuid
  field :full_name do |user|
    "#{user.first_name} #{user.last_name}"
  end
end
```

**Comment by das3in** [comment]
Been experimenting with this on a client project. I think something like what you suggest @philipqnguyen would work but it feels bulky. It'd be cool if we could infer it.

In regards to the example above... shouldn't `full_name` be a method on the `User` model anyway? Is a serializer really the place to be doing that?

**Comment by ojab** [comment]
Well, should or shouldn't it be in the model is another question.
In theory computed fields can use kwarg to set fields that are used, i. e. something like
```ruby
class UserBlueprint < Blueprinter::Base
  identifier :uuid

  field :full_name, using: %i[first_name last_name] do |user|
    "#{user.first_name} #{user.last_name}"
  end
end
```

Anyway, it's not the only corner case. Something like 
```ruby
class ModelBlueprint < Blueprinter::Base
  field :am_field
end

models = Model.joins(:another_model).select('another_models.fields as am_field')
```
will also be broken, since `models.select(:am_field)` will fail and I'm sure there are many other examples.

**Comment by philipqnguyen** [comment]
@das3in there are many cases I've encountered where defining a method directly in the model felt unnecessary as it was so specific to the JSON response only, and therefore I would like to have that support of defining a custom field directly in the blueprint. 

You're right @das3in that it would be nice to have it be inferred, but I can't think of a way right now of how that could work. Again open to ideas on this.

@ojab I think the case you suggested is an extreme corner case, and that it's not necessarily a problem that Blueprinter should handle for anyways. That should be up to the responsibility of the developer using the gem to ensure such a conflict did not exist.

**Comment by das3in** [comment]
That makes sense. I'm getting started on an implementation of your idea - we'll see how it goes

**Comment by philipqnguyen** [comment]
closing for now due to inactivity 😄
