### ISSUE TITLE
Serialize datetime field

### ISSUE THREAD

**Issue by philipqnguyen** [procore/blueprinter#70]
How should Blueprinter serialize datetime fields?

Should Blueprinter automatically check each fields to see if it is a DateTime or Time object?
Or should we provide a way for the user to specify that a field is of DateTime or Time? 

Either way, we also would need to allow users to customize the datetime format that they would like to serialize to.

**Comment by psloomis** [comment]
How about this:
```ruby
class InsuranceBlueprint < Blueprinter::Base
  field :expiration_date, date_format: "%d %m %Y"
end
```
If `date_format` is passed as an option, we just assume the object is a `DateTime` or `Time` or `Date`.

**Comment by philipqnguyen** [comment]
I definitely like that idea @psloomis would you like to take a stab at a PR for that?

**Comment by mcclayton** [comment]
Hi @anlek, I believe the possibility of having a globally set datetime format was being discussed in issue: https://github.com/procore/blueprinter/issues/120
