### ISSUE TITLE
view terminology

### ISSUE THREAD

**Issue by toobulkeh** [procore/blueprinter#77]
Hey guys, just checking out your library for the first time, so feel free to close this due to early ignorance, but I just wanted to discuss your concept of the "view" terminology.

Since views are a well established keyword/role in Rails, why do you override the term with the `view` method, instead of using something more unique? FactoryBot uses the term `traits` for this same purpose. Or you could use the "branding" of a blueprint from the construction industry and do something like "layer", ["cross section", or "floor"](http://www.the-house-plans-guide.com/how-to-read-blueprints.html).

😃

**Comment by philipqnguyen** [comment]
No problem, glad to discuss!

You're right that `view` has an established usage in Rails, however I also think that the same meaning of `view` already in Rails can be used in the context of Blueprinter. Just like you would create HTML views that you expect ActionController to render, you also create JSON views for Blueprinter to render.

While using unique terminologies might be nice, if the terminologies are too unique, it might become harder for people to understand what the methods are actually used for. The README.md would be larger as we would have to explain all the new terminologies we are using.

**Comment by philipqnguyen** [comment]
Closing for now, feel free to reopen if you or anyone else thinks it warrants more discussion.
