### ISSUE TITLE
Aliasing fields?

### ISSUE THREAD

**Issue by toobulkeh** [procore/blueprinter#79]
Is there a way to alias fields besides creating completely new fields in the Blueprint?

```ruby
class UserBlueprint < Blueprinter::Base
  identifier :uuid

  fields {first_name: :firstName}, :last_name, :email
  field first_name, as: :firstName
  ...
```

**Comment by philipqnguyen** [comment]
It is supported by using the :name option like so:

field :first_name, name: :firstname

**Comment by toobulkeh** [comment]
Ah, that's kinda hidden in the README. Thanks!
