### ISSUE TITLE
Automatic Eager Loading on Associations?

### ISSUE THREAD

**Issue by toobulkeh** [procore/blueprinter#82]
```ruby
class ProductLineBlueprint < ApplicationBlueprint
  identifier :id
  
  fields :name

  view :extended do
    association :product_features, name: :features, blueprint: ProductFeatureBlueprint, view: :extended
  end
end
```

```ruby
class ProductFeatureBlueprint < ApplicationBlueprint
  identifier :id
  
  fields :name, :type

  view :extended do
    association :feature_options, name: :options, blueprint: FeatureOptionBlueprint
  end
end
```

In this example, ProductFeatures and FeatureOptions should be eager loaded when necessary.

**Comment by philipqnguyen** [comment]
Thanks for bringing this up @toobulkeh. Should eagerloading an association be the responsibility of Blueprinter or should the ActiveRecord object passed to Blueprinter be already eagerloaded?

I think it should already be eagerly loaded before being passed to Blueprinter. Having Blueprinter eagerload the association could be tricky. For example, developers may not be aware that Blueprinter already eagerloads for them (unless you make it optional). Additionally, eagerload can be pretty complex, especially cases where it is not obvious that an eagerload is needed. For example:

```ruby
# inside a User.rb model
class User < ActiveRecord::Base
  has_one :dog
  def dog_name
    dog.name
  end
end

# inside a UserBlueprint
field :dog_name # Blueprinter would not know to eagerload this
```

Pinging @dlcarter @AllPurposeName for their thoughts

**Comment by toobulkeh** [comment]
Agree with your points. I think I was facing a case where I couldn't eager load in the controller for some reason. Let me see if I can come up with a better example. Thanks!

**Comment by philipqnguyen** [comment]
Closing this issue for the same reason as closing #96

Re-open if you think otherwise.
