### ISSUE TITLE
Naming associations

### ISSUE THREAD

**Issue by ekampp** [procore/blueprinter#87]
Hey there. 

This is both a question for clarification and perhaps a feature suggestion.

I love the association pattern. But I would like to be able to rename it in the presentation layer so that the generated JSON is semantically clean regardless of the underlying system's limitations. 

An example here is that I have a Product model in Rails. This has a `has_many :product_errors` relation because rails don't support renaming the built-in errors relation.

Here is my blueprint class: 

```ruby
class ProductBlueprint < Blueprinter::Base
  identifier :sku
  association :product_errors, blueprint: ProductErrorBlueprint
end
```

This generates the following JSON:

```json
[
 {
    "sku": "prod1",
    "product_errors": []
  }
]
```

I would like to be able to rename the association in the generated JSON to something like `errors` for a more precise JSON result. Perhaps something like adding `as: :errors` to the association would be a solution here? 

```ruby
class ProductBlueprint < Blueprinter::Base
  identifier :sku
  association :product_errors, as: :errors, blueprint: ProductErrorBlueprint
end
```

Which would then generate: 

```json
[
 {
    "sku": "prod1",
    "errors": []
  }
]
```

Let me know if what you think. 

Thanks.

**Comment by ekampp** [comment]
Never mind. After looking at the source code this can be done with the `name: :new_name` option. Perhaps this could be clearer in the documentation?

**Comment by philipqnguyen** [comment]
You're right! It needs better documentation! I added issue #88 and I'll try to get to it next week. You're also welcome to document it and make a PR if you want to as well. Thanks for bringing this up @ekampp

**Comment by ekampp** [comment]
Btw f***ing nice library this is! It's my new favorite tool.

**Comment by philipqnguyen** [comment]
Glad you find this helpful =)

**Comment by ekampp** [comment]
We do need to get the `ApplicationBlueprint` pattern in place (#80). That would deduplicate a lot of code.
