### ISSUE TITLE
Pass a block to an association

### ISSUE THREAD

**Issue by Systho** [procore/blueprinter#90]
Sometimes I'd like to expose an association which is not directly  callable on the record itself. My main case is calling the association on a belongs_to or a has_one "middle" object.

I thought I could pass a block to the association like I do for the normal fields but it does not happen to work.

Do you think it would be possible for the `association`to work like the `field` and accept an optional block returning an AR::Relation ?

**Comment by philipqnguyen** [comment]
Yes, I think this feature is needed. Would you (or anyone) be willing to make a PR? I would too, but it will take me a week or to before I can get to it, I've been a bit busy.

**Comment by Systho** [comment]
Unfortunately I'm not sure of my availability during the next days, I may make a PR but it's very inprobable

**Comment by philipqnguyen** [comment]
resolved by #106
