### ISSUE TITLE
options lost

### ISSUE THREAD

**Issue by Systho** [procore/blueprinter#91]
You'r assigning a new hash to a local variable named `options` thereby shadowing the options parameter received by the method

https://github.com/procore/blueprinter/blob/e9f5bd9854c4a9731cb1841436888ce70aab9570/lib/blueprinter/base.rb#L94

**Comment by philipqnguyen** [comment]
Options aren't lost. The original `options` are merged back into the new local variable `options` in line 98:
https://github.com/procore/blueprinter/blob/e9f5bd9854c4a9731cb1841436888ce70aab9570/lib/blueprinter/base.rb#L94-L98

**Comment by philipqnguyen** [comment]
unless I'm missing something?

**Comment by Systho** [comment]
Oh actually you're right, but it used to not be the case on old ruby versions. Sorry about that.

It might still be more readable to give the resulting `options` local variable another name to avoid the shadowing but You're indeed right : it works, sorry for false alarm.

**Comment by philipqnguyen** [comment]
No problem! I'm closing this issue for now, but you make a good point about readability on the variable naming, and will gladly accept PRs from anyone on that.
